backend:
  # name: github
  # repo: esteinborn/nysds-site
  # branch: main
  name: git-gateway
  branch: main
# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets/img" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "component" # Used in routes, e.g., /admin/collections/blog
    label: "Component" # Used in the UI
    folder: "src/content/components" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Short Description", name: "description", widget: "string" }
      - { label: "Long Description", name: "long_description", widget: "markdown" }
      - { label: "Navigation Order", name: "navOrder", widget: "number" }
      - { label: "image", name: "image", widget: "file" }
      - { label: "code", name: "code", widget: "code" }
      - { label: "Do", name: "do", widget: "markdown" }
      - { label: "Dont", name: "dont", widget: "markdown" }
      - { label: "Body", name: "body", widget: "markdown" }
      